# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shopin' do
    pod 'Alamofire', '~> 4.3'
    pod 'SVProgressHUD'
    pod 'IQKeyboardManagerSwift'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopin

end
